# Project-wide Gradle settings.

# JVM memory settings (increase heap size to avoid Java heap space errors)
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# Enable AAPT2 PNG crunching
android.enablePngCrunchInReleaseBuilds=true

# Architectures
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

# New Architecture
newArchEnabled=true

# Hermes JS engine
hermesEnabled=true

# Expo image support
expo.gif.enabled=true
expo.webp.enabled=true
expo.webp.animated=false

# Network inspector
EX_DEV_CLIENT_NETWORK_INSPECTOR=true

# Packaging
expo.useLegacyPackaging=false

# Use JSC instead of Hermes
expo.jsEngine=jsc
